package com.workq.tracelisteners.model;

public enum TaskChangeType {

    ACTIVATED, CLAIMED, STARTED, COMPLETED, FAILED, RELEASED, NOMINATED, UPDATED, ASSIGNMENT_ADDED, ASSIGNMENT_REMOVED,
    REASSIGNED;
}
